### ISSUE TITLE
each database has same table name

### ISSUE THREAD

**Issue by liyu001989** [cviebrock/sequel-pro-laravel-export#13]
First, this bundle is very useful 👍 Thank you!

I have many databases, each of them has a table called `users`, when I export one, it export all of them.

<img width="430" alt="2016-11-18 11 33 02" src="https://cloud.githubusercontent.com/assets/2981799/20417788/e00e6386-ad82-11e6-9f42-2423d8b5a031.png">
<img width="243" alt="2016-11-18 11 34 13" src="https://cloud.githubusercontent.com/assets/2981799/20417798/f74e0ea2-ad82-11e6-9608-1593a38f12ee.png">

**Comment by cviebrock** [comment]
Can you pull the `master` branch and re-install the bundle? It appears to be fixed locally, but would love confirmation!

**Comment by liyu001989** [comment]
ok  it works 👍
