### ISSUE TITLE
No migration file created.

### ISSUE THREAD

**Issue by jonjrwhite** [cviebrock/sequel-pro-laravel-export#19]
I've just installed this bundle having cloned from github and double-clicked the “ExportToLaravelMigration.spBundle” installer.

I can see the export option in my Bundles menu in Sequel Pro but no migration file is created on my desktop.

I'm running Sequel Pro 1.1.2 on macOS Sierra 10.12.4.

**Comment by cviebrock** [comment]
I'm running the same versions and don't see to have this issue.

I just pushed a new version (1.1.0) with a few changes.  Exports should now get put into `~/Desktop/SequelProLaravelExport` so maybe try again?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
