### ISSUE TITLE
Query error

### ISSUE THREAD

**Issue by n8jadams** [cviebrock/sequel-pro-laravel-export#20]
When I export this one specific table, it doesn't work and I get a little notification: "Query error."

Here is the sql table info:

```
CREATE TABLE `call` (
  `call_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `account_number` varchar(12) NOT NULL,
  `caller_phone` varchar(32) DEFAULT '',
  `caller_name` varchar(64) DEFAULT '',
  `caller_address` varchar(128) DEFAULT '',
  `caller_city` varchar(64) DEFAULT '',
  `call_type` varchar(64) DEFAULT '',
  `call_description` text NOT NULL,
  `agent` varchar(64) DEFAULT '',
  `timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `is_resolved` tinyint(1) DEFAULT '0',
  `customer_type` tinyint(4) DEFAULT '0',
  `caller_account_number` varchar(32) DEFAULT '',
  PRIMARY KEY (`call_ID`),
  KEY `account_number` (`account_number`),
  KEY `timestamp` (`timestamp`)
) ENGINE=MyISAM AUTO_INCREMENT=1405309 DEFAULT CHARSET=latin1;
```
Every other table in the database I was trying to migrate worked flawlessly (huge thumbs up), just this one threw it off for some reason.

If it's necessary to know, I'm using Sequel Pro 1.1.2 on Mac El Capitan.

**Comment by cviebrock** [comment]
I wasn't escaping the table name correctly in the export script:

```sql
SHOW INDEXES FROM call;
```

I've changed that to the following, which now works;

```sql
SHOW INDEXES FROM `call`;
```

Version 1.2.0 should be tagged shortly.  Thanks for the find!

**Comment by n8jadams** [comment]
Is it done? I saw that you pushed a change and I immediately tested it. Now all of my tables are giving the "Query error." Even this `call` one.

**Comment by cviebrock** [comment]
Yeah, I untagged the release ... something else broke, and I'm working on it now.

**Comment by n8jadams** [comment]
Thanks man. This is an awesome piece of software.

**Comment by cviebrock** [comment]
This took embarrassingly longer than I wanted, but could you try the most recent version before I tag it?  I also took the opportunity to clean up the output a bit with more useful info and/or error messages.

If it works for you, I'll tag and bag it. ;)

**Comment by n8jadams** [comment]
Worked like a charm!

**Comment by cviebrock** [comment]
Awesome ... thanks!  Versino 1.2.0 is now tagged (with a bit fancier output now too).
