### ISSUE TITLE
What alternative to use to replace the Xethron migration generator, which is obsolete since Laravel 5.8?

### ISSUE THREAD

**Issue by The77thSuperSoldier** [cviebrock/sequel-pro-laravel-export#32]
I would not like to go back to an earlier version of Laravel to be able to use Xethron :-(. Can you please offer me another solution?

**### I've run the following command in my laravel 6.4 project but without success**

prompt > composer require --dev "xethron/migrations-generator"

Using version ^2.0 for xethron/migrations-generator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - xethron/migrations-generator v2.0.0 requires way/generators dev-feature/laravel-five-stable -> no matching package found.
    - Conclusion: remove laravel/framework v6.4.1
    - Conclusion: don't install laravel/framework v6.4.1

    - xethron/migrations-generator v2.0.1 requires xethron/laravel-4-generators ~3.1.0 -> satisfiable by xethron/laravel-4-generators[3.1.0, 3.1.1].

    - xethron/migrations-generator v2.0.2 requires xethron/laravel-4-generators ~3.1.0 -> satisfiable by xethron/laravel-4-generators[3.1.0, 3.1.1].

    - xethron/laravel-4-generators 3.1.0 requires illuminate/support ~5.0 -> satisfiable by illuminate/support[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26,..., v5.8.9].

    - xethron/laravel-4-generators 3.1.1 requires illuminate/support ~5.0 -> satisfiable by illuminate/support[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26,..., v5.8.9].

**Comment by cviebrock** [comment]
I think maybe you posted this to the wrong project?  I'm not involved with xethron/migrations-generator in any way.

That said, it looks like it isn't supported anymore ... so you could use my package!

Keep in mind: my package isn't for Laravel.  It's a plug-in bundle for (Sequel Pro)[https://www.sequelpro.com/] to export tables to Laravel migration files.  Everything you need to know should be in the (README.md)[https://github.com/cviebrock/sequel-pro-laravel-export/blob/master/README.md].  Let me know if you run into trouble.
