### ISSUE TITLE
DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 

### ISSUE THREAD

**Issue by hyhnet** [cviebrock/sequel-pro-laravel-export#33]
Hi there,

First, thanks for this awesome tool!

lost  ON UPDATE CURRENT_TIMESTAMP

For example:

```sql
`CREATE TABLE `test` (
  `id` int(10)  NOT NULL,
  `updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```
... generates this migration ...

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTestTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('test', function (Blueprint $table) {
            $table->integer('id');
            $table->timestamp('updated')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('test');
    }
}
```

I'm using bundle version 1.6.0 with Sequel Pro 1.1.2 version 4541 (602e11a) on Mysql 5.7.28 (Docker 19.03.5).

**Thank you!**

**Comment by cviebrock** [comment]
It's been a while ... how would you represent `ON UPDATE CURRENT_TIMESTAMP` in Laravel's Schema?

**Comment by cviebrock** [comment]
Actually, it looks like if you drop the `->nullable()` for that column, running the migration should give you the correct `ON UPDATE`.  This is a MySQL thing, not a Laravel thing.

That said, I'll see if I can fix the package to handle this correctly.

**Comment by cviebrock** [comment]
@hyhnet Can you give version 1.7.0 a try?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
