### ISSUE TITLE
error with input type "SET"

### ISSUE THREAD

**Issue by brada1703** [cviebrock/sequel-pro-laravel-export#34]
Hi there,

I noticed an error when exporting a table from Sequel Pro. For any inputs with the type "SET", I would get the following:

`$table->UNKNOWN:set('flavours')->default('strawberry');`

Desired output:

`$table->set('flavours', ['strawberry', 'vanilla'])->default('strawberry');`

I am using Laravel 7, Sequel Pro Build 5446.

(Finally, thanks so much for developing this Colin! You've saved me a ton of time. 😊 )

**Comment by cviebrock** [comment]
Sorry for the delay.

I'll get a fix out for this as soon as possible!

**Comment by cviebrock** [comment]
I lied:  "as soon as possible" apparently means 4-6 months. 😄 

This should be fixed now in the latest release (1.8.1).  Sorry for the delay ... really, this time!
