### ISSUE TITLE
"No table selected" in Sequel Ace

### ISSUE THREAD

**Issue by mehrdd** [cviebrock/sequel-pro-laravel-export#42]
Hi,
I'm having a problem with Sequel Ace :

![image](https://user-images.githubusercontent.com/1578360/118248986-29045a80-b4ba-11eb-9fe2-43d101e04d52.png)

At first i used "2.0.1 Release" and then tried to build it myself.. none of them worked for me and it says: "No table selected."

macOS: Big Sur 11.3.1
Sequel Ace: 3.3.1

**Update:**
The problem is the latest stable version of Sequel Ace:
https://github.com/Sequel-Ace/Sequel-Ace/issues/1038

**Comment by cviebrock** [comment]
I'm having trouble in general with Sequel Ace and my bundle.  Not sure what's going on, but I've opened https://github.com/Sequel-Ace/Sequel-Ace/issues/1107 to try and figure it out.

I'll report back!

**Comment by cviebrock** [comment]
Finally getting around to closing this issue.  The package works much more consistently with the latest versions of Sequel Ace (and the package).
