### ISSUE TITLE
JSON field type not mapped correctly

### ISSUE THREAD

**Issue by tomcoonen** [cviebrock/sequel-pro-laravel-export#7]
Field creation syntax:
```
`some_json_field` json DEFAULT NULL
```
Creates this migration:
```
 $table->UNKNOWN:json('some_json_field')->nullable();
```
Which should be:
```
$table->json('some_json_field')->nullable();
```

**Comment by cviebrock** [comment]
Thanks Tom.  None of the instances of MySQL I have handy support JSON columns, so would you mind testing the `master` version of the package and see if the change I added fixes it?

Thanks for the testing!

**Comment by tomcoonen** [comment]
Fixed!

**Comment by cviebrock** [comment]
Version 1.0-beta.3 has this and the increments bug (#6) fix, plus a fix for ENUMs that I found.  Thanks again!
