### ISSUE TITLE
No export, after updating plugin.

### ISSUE THREAD

**Issue by Kreshnik** [cviebrock/sequel-pro-laravel-export#8]
Hi there,

After I have updated the plugin to the latest version. The export does not seem to function anymore. After I hit export, I do get a small tooltip `please select a`
<img width="583" alt="screen shot 2016-10-17 at 10 52 26 pm" src="https://cloud.githubusercontent.com/assets/1788349/19455272/d1e7333e-94bc-11e6-8f38-ee847042dbe3.png">
Is there any other information I can provide, for further debugging?.

Great job done so far, keep it up!

**Comment by cviebrock** [comment]
You need to select a table from the right side bar first, then try the export.

**Comment by Kreshnik** [comment]
Tried that, but still, nothing happens.
<img width="919" alt="screen shot 2016-10-17 at 11 04 48 pm" src="https://cloud.githubusercontent.com/assets/1788349/19455686/4811942c-94be-11e6-84e0-9142a0154076.png">

**Comment by cviebrock** [comment]
I don't think you can select more than one table

**Comment by Kreshnik** [comment]
Ouuu, I see. Shall I create then a few feature request (wishes) issues?

**Comment by cviebrock** [comment]
You could ... but I'm pretty sure that Sequel Pro doesn't expose a multiple-list of tables to bundle developers.  So I think, for now, it's gotta be one at a time, unfortunately.

**Comment by Kreshnik** [comment]
I understand, even though I am not familiar with Sequels Pro API, there seems to be a command called `SP_SELECTED_TABLES` maybe it's work having a look at it. :)
