### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by Kreshnik** [cviebrock/sequel-pro-laravel-export#9]
It would be nice to have some kind of error output if something doesn't work. Currently, if the plugin for whatever reason doesn't work, you get no error output, which you could use to further assist in debugging the issue.

**Comment by cviebrock** [comment]
I agree. Keep in mind, please, that Sequel Pro bundles aren't super integrated into the app itself.  Basically, they fork out to a shell script, set a bunch of environment variables for you to use to access things like the table/row/data that was selected when the bundle was launched, and a kinda weird way to run your own queries (write your custom SQL to a file, then read another file for the output).

User interface is pretty much limited to tooltips and simple HTML output in a pop-up window.

I could do some stuff with the pop-up window, but again, it's not going to be super complex.

**Comment by Kreshnik** [comment]
I understand, thank you @cviebrock for taking the time to elaborate this. The good thing about this plugin is, that it can only become better :)
